
//This file is reachable from all other js files (you have access to the variables in here)

var UNIQUE_CITIES = [
    'Alabama',
    'Arkansas',
    'Arizona',
    'California',
    'Colorado',
    'Connecticut',
    'District of Columbia',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Iowa',
    'Idaho',
    'Illinois',
    'Indiana',
    'Kentucky',
    'Louisiana',
    'Massachusetts',
    'Maryland',
    'Maine',
    'Michigan',
    'Minnesota',
    'Missouri',
    'North Carolina',
    'Nebraska',
    'New Hampshire',
    'New Jersey',
    'Nevada',
    'New York',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'Tennessee',
    'Texas',
    'Utah',
    'Virginia',
    'Vermont',
    'Washington',
    'Wisconsin',
    'West Virginia'
];

var VARIABLE_NAMES = [
    "Number of Cities",
    "Average 2020/2021 household income",
    "Historic Percent Change in Household Income 1984-2019",
    "Average Yealry Historic Percent Change in Income 1984-2019",
    "Minimum Wage", 
    "Average House Price 2020/2021",
    "Percent Change in Historic House Prices 2000-2019",
    "Average Yearly Percent Change in Housing Prices 2000-2019",
    "# of Violent Crime",
    "# of Property Crime",
    "Property Crime Per Capita",
    "Violent Crime Per Capita",
    "Total Crime Per Capita",
    "Pop",
    "Men",
    "Women",
    "VotingAge",
    "Employed",
    "Hispanic",
    "White",
    "Black",
    "Native",
    "Asian",
    "Pacific",
    "Average Income",
    "Income Per Capita",
    "Poverty",
    "ChildPoverty",
    "Professional",
    "Service",
    "Office",
    "Construction",
    "Production",
    "Drive",
    "Carpool",
    "Transit",
    "OtherTrans",
    "WorkAtHome",
    "MeanCommute",
    "PrivateWork",
    "SelfEmployed",
    "FamilyWork"
    ,"Unemployment",
    "Population"
];